12-03 14:01:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: 複数のプライマリキーを定義しようとしました
Attempt to define a second primary key; SQL statement:
create table sample (
  ID INT PRIMARY KEY,
  TEST_INT INT,
  TEST_BOOLEAN BOOLEAN,
  TEST_TINYINT TINYINT,
  TEST_SMALLINT SMALLINT,
  TEST_BIGINT BIGINT,
  TEST_IDENTITY IDENTITY,
  TEST_DECIMAL DECIMAL(20, 2),
  TEST_DOUBLE DOUBLE,
  TEST_REAL REAL,
  TEST_TIME TIME,
  TEST_DATE DATE,
  TEST_TIMESTAMP TIMESTAMP,
  TEST_BINARY BINARY(1000),
  TEST_OTHER OTHER,
  TEST_VARCHAR VARCHAR(20),
  TEST_VARCHAR_IGNORECASE VARCHAR_IGNORECASE,
  TEST_CHAR CHAR(20),
  TEST_BLOB BLOB,
  TEST_CLOB CLOB,
  TEST_UUID UUID,
  TEST_ARRAY ARRAY
) [90017-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.command.ddl.CreateTable.setPrimaryKeyColumns(CreateTable.java:240)
	at org.h2.command.ddl.CreateTable.addConstraintCommand(CreateTable.java:82)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5221)
	at org.h2.command.Parser.parseCreate(Parser.java:3805)
	at org.h2.command.Parser.parsePrepared(Parser.java:323)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:250)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:414)
	at org.h2.engine.Session.prepareCommand(Session.java:363)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
12-03 14:04:22 jdbc[4]: null
org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-170]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:645)
	at org.h2.server.web.WebApp.login(WebApp.java:899)
	at org.h2.server.web.WebApp.process(WebApp.java:205)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:164)
	at org.h2.server.web.WebThread.process(WebThread.java:137)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.h2.jdbc.JdbcSQLException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 14 more
12-03 14:51:14 jdbc[5]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:645)
	at org.h2.server.web.WebApp.login(WebApp.java:899)
	at org.h2.server.web.WebApp.process(WebApp.java:205)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:164)
	at org.h2.server.web.WebThread.process(WebThread.java:137)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)

org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-170]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:645)
	at org.h2.server.web.WebApp.login(WebApp.java:899)
	at org.h2.server.web.WebApp.process(WebApp.java:205)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:164)
	at org.h2.server.web.WebThread.process(WebThread.java:137)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.h2.jdbc.JdbcSQLException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 14 more
